### ISSUE TITLE
SQL Server 2000 not supported??

### ISSUE THREAD

**Issue by gandalivs** [Miramac/vq-mssql#1]
Help please..i need to connect SQL Server2000 with my node js app..
this my connection with your lib
```

var MsSqlConnection = require('vq-mssql');

var db1 = new MsSqlConnection({
    connectionSettings: {
        driver: '{SQL Server Native Client 11.0}',
        server: cfg2000.db_server_ip,
        database: cfg2000.db_name,
        dbUser: cfg2000.db_user,
        dbPassword: cfg2000.db_password
    }
}); 
app.get('/pol', function (req, res) {
    db1.query('select count(*) from ihp_rcp', function(err, result) {
        if(err){
            console.log(err);
        }else{
            console.log(result);
        }
       
      });
});
```

and this error , any solution please...??

`{ Error: [Microsoft][SQL Server Native Client 11.0]SQL Server Native Client 11.0 does not support connections to SQL Server 2000 or earlier versions. sqlstate: '08001', code: 22 }
`

**Comment by Miramac** [comment]
Hi @gandalius,

you can try an other driver:

````
var db1 = new MsSqlConnection({
    connectionSettings: {
        driver: '{SQL Server Native Client 10.0}',
        server: cfg2000.db_server_ip,
        database: cfg2000.db_name,
        dbUser: cfg2000.db_user,
        dbPassword: cfg2000.db_password
    }
}); 
````
Or use a ConnenctionString supported by MSSQL 2000: https://www.connectionstrings.com/sql-server-2000

I hope this helps you!

**Comment by gandalivs** [comment]
Thank you very much :+1: @Miramac 
but there are still some obstacles in my code...
when i change my conecction..

```
var db1 = new MsSqlConnection({
    connectionSettings: {
        driver: '{SQL Server Native Client 10.0}',
        server: cfg2000.db_server_ip,
        database: cfg2000.db_name,
        dbUser: cfg2000.db_user,
        dbPassword: cfg2000.db_password,
        useTrustedConnection: true
    }
});
```
i have this warning and my db connection still failed

`{ Error: [Microsoft][SQL Server Native Client 10.0][SQL Server]Login failed for user 'BAMS\Guest'. sqlstate: '28000', code: 18456 }`

i try to change again my connection 
```
connectionSettings: {
        driver: '{SQL Server Native Client 10.0}',
        server: cfg2000.db_server_ip+'\"'+cfg2000.db_instance_name,
        database: cfg2000.db_name,
        dbUser: cfg2000.db_user,
        dbPassword: cfg2000.db_password,
        useTrustedConnection: true,
    }
```
and the error warning like this 

```
{ Error: [Microsoft][SQL Server Native Client 10.0]VIA Provider: The specified module could not be found.
 sqlstate: '08001', code: 126 }
```

please..can you give full example connection component on my case??whetever connectionSetting or connectionString??

thx again master..

**Comment by Miramac** [comment]
I think the error in your connenction is `useTrustedConnection: true`. It should be only true if you use integrated windows authentication, if you use user and password you must set it to `false`

try: 
````javascript
var db1 = new MsSqlConnection({
    connectionSettings: {
        driver: '{SQL Server Native Client 10.0}',
        server: cfg2000.db_server_ip,
        database: cfg2000.db_name,
        dbUser: cfg2000.db_user,
        dbPassword: cfg2000.db_password,
        useTrustedConnection: false
    }
});
````

This is my suggestion for the second example:
````javascript
connectionSettings: {
        driver: '{SQL Server Native Client 10.0}',
        server: cfg2000.db_server_ip+'\\'+cfg2000.db_instance_name,
        database: cfg2000.db_name,
        dbUser: cfg2000.db_user,
        dbPassword: cfg2000.db_password,
        useTrustedConnection: false,
    }
````

good luck :)

**Comment by gandalivs** [comment]
Thank you, again for a response @Miramac , but this still not nowrking for sqlserver2000, maybe i'll try another library.
But this library work fine with SqlServer 2008. :)

**Comment by Miramac** [comment]
I'm sorry to hear that. I have also never tested it with SQL Server 2000...

**Comment by gandalivs** [comment]
im update my sql 2000 server pack 3,
https://www.microsoft.com/en-us/download/confirmation.aspx?id=17155

work done
